apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service #test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend
        image: yashwanthydg/frontend-service:c0636cc8cdaaea046c0e5cac4db0bbac678be786
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008 
